name: run main.py

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/15 * * * *" # 15분 마다

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp
          pip install motor
          pip install pydantic
          pip install pytz
          pip install aiohttp-retry
          pip install python-dotenv

      - name: execute data scrapping
        env:
          DB_URL: ${{ secrets.DB_URL }}
          PERIOD_MIN: ${{ secrets.PERIOD_MIN }}

        run: python main.py
